In [1]:
import numpy as np 

### Tạo numpy array từ list python 

In [2]:
np.array([1,2,4,5,6,7,8])  # same type 

array([1, 2, 4, 5, 6, 7, 8])

In [3]:
 np.array([3.14, 3, 6, 10], dtype = np.float32) # chon kieu du lieu theo y muon 

array([ 3.14,  3.  ,  6.  , 10.  ], dtype=float32)

In [5]:
[range(i,i+3) for i in [2,4,6,8,10,12,14]]

[range(2, 5),
 range(4, 7),
 range(6, 9),
 range(8, 11),
 range(10, 13),
 range(12, 15),
 range(14, 17)]

In [4]:
# tao ra numpy array 2D 
np.array([range(i,i+3,1) for i in [2,4,6,8,10,12,14]])

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10],
       [10, 11, 12],
       [12, 13, 14],
       [14, 15, 16]])

### Tạo array từ đầu 

In [19]:
np.zeros((8,14,14), dtype=np.int32)  # tao ra shape full zeros

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
np.ones((3,3) , dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [8]:
np.full((3,3), 1.4142)

array([[1.4142, 1.4142, 1.4142],
       [1.4142, 1.4142, 1.4142],
       [1.4142, 1.4142, 1.4142]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# tao ra cac gia tri cach deu nhau
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.random((3,3,3))  # truyen vao shape

array([[[0.33822421, 0.44527482, 0.56313524],
        [0.77339143, 0.21455692, 0.79360518],
        [0.59750462, 0.96135675, 0.52598386]],

       [[0.7467209 , 0.27964443, 0.75699253],
        [0.6160223 , 0.71883506, 0.30673874],
        [0.99559614, 0.6248221 , 0.43822822]],

       [[0.64351164, 0.02028515, 0.83777957],
        [0.88055033, 0.45484432, 0.38814896],
        [0.69132223, 0.04285883, 0.32953997]]])

In [24]:
np.random.randint(0,4,(3,3))  # random tu 0 den 4 vs shape = (3,3)

array([[1, 3, 3],
       [1, 2, 2],
       [1, 1, 1]])

In [27]:
np.eye(5) # tao ra matrix đơn vị 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.empty((3,3), dtype=np.float32) # khỏi tạo ra shape trong địa chỉ bộ nhớ 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### Universal Functions

In [2]:
# import thu vien 

import numpy as np
np.random.seed(0)  # seed for reproducibility random cac gia tri giong nhau trong.

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  

In [3]:
print (x1)
print ()
print (x2)
print ()
print (x3)

[5 0 3 3 7 9]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [4]:
x1.shape
print(x1)

[5 0 3 3 7 9]


In [5]:
x2.shape

(3, 4)

In [6]:
x3.shape

(3, 4, 5)

In [7]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [8]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [9]:
x3.dtype # kieu du lieu cua mang

dtype('int64')

In [10]:
x3.itemsize # kich thuoc cua mang

8

In [11]:
x3.nbytes # byte

480

In [12]:
x3.itemsize * x3.size

480

### Array Indexing: Accessing Single Elements

In [13]:
x3[-1][-1][-2]# lay index tu cuoi ve dau

6

In [14]:
x1[0] = 3.4324 # tu dong loai bo dau phay dong
x1[0]

3

In [15]:
x2[1][1] = -5 # gia tri bi thay doi bang cach gan
x2

array([[ 3,  5,  2,  4],
       [ 7, -5,  8,  8],
       [ 1,  6,  7,  7]])

### Array Slicing: Accessing Subarrays

array slicing : accessing subarrays 
 
 x[start:stop:step]


In [16]:
x =  np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]

array([0, 1, 2, 3, 4])

z

### One-dimensional subarrays

In [18]:
x[5:]

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]

array([4, 5, 6])

In [27]:
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
x[1::2]

array([1, 3, 5, 7, 9])

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
x[5::-2]

array([5, 3, 1])

### multi-dimensional subarrays

In [19]:
x2
x2.shape

(3, 4)

In [20]:
x2[:2,:3] # two rows , three columns

array([[ 3,  5,  2],
       [ 7, -5,  8]])

In [21]:
x2[:2, :: 3]

array([[3, 4],
       [7, 8]])

### finally, subarray dimensions can even be reversed together: 

In [22]:
x2[::-1, :: -1]

array([[ 7,  7,  6,  1],
       [ 8,  8, -5,  7],
       [ 4,  2,  5,  3]])

In [38]:
x2

array([[ 3,  5,  2,  4],
       [ 7, -5,  8,  8],
       [ 1,  6,  7,  7]])

### Accessing array rows and columns

### one commonly need routine is accessing of single rows or columns of an array. this can be done by combining indexing and slicing, using an empty slice marked by a single colon

In [23]:
print (x2[:, 0])

[3 7 1]


In [24]:
print(x2) 

[[ 3  5  2  4]
 [ 7 -5  8  8]
 [ 1  6  7  7]]


In [25]:
x2_sub = x2[:2, :3]

In [27]:
print(x2_sub)

[[ 3  5  2]
 [ 7 -5  8]]


### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:


In [41]:
x2_sub_copy  = x2[:2,:2].copy() # copy data x2 to x2_sub_array 
print(x2_sub_copy)

[[ 3  5]
 [ 7 -5]]


 If we now modify this subarray, the original array is not touched:`

In [42]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7 -5]]


### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [43]:
grid= np.random.randint(10, size= (4,5))
grid

array([[4, 2, 0, 3, 2],
       [0, 7, 5, 9, 0],
       [2, 7, 2, 9, 2],
       [3, 3, 2, 3, 4]])

In [31]:
grii  = np.arange(1,13).reshape(4, 3)
# arange la so luong number can dung 
# size la kich thuoc cua array 

In [32]:
grii

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
print(x1)
x2 = x1.reshape((2,3))
print(x2)

[3 0 3 3 7 9]
[[3 0 3]
 [3 7 9]]


In [34]:
y = np.arange(1,11)

In [35]:
y.reshape(2,5) 
# the new matrix reshape  just equa of number before

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
x[:, np.newaxis] # doi hang thanh cot
x[np.newaxis, :] # doi cot thanh hang

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [56]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [57]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [54]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print()
print(np.vstack([x,y]))  # chuyen theo chieu doc cua mang
print()
print (np.hstack([x,y])) # chuyen theo chieu ngang cua mang

[1 2 3 3 2 1]

[[1 2 3]
 [3 2 1]]

[1 2 3 3 2 1]


In [38]:
gird = np.arange(16).reshape ((4,4))

In [39]:
gird

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
upper , lower = np.vsplit(grid,[3])

In [118]:
print (upper)
print("\n")
print (lower)

[[9 0 9 6 5]
 [3 1 8 0 4]
 [9 6 5 7 8]]


[[8 9 2 8 6]]


In [119]:
left , right = np.hsplit(gird, [2])

In [120]:
print ( left)
print("\n")
print (right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Array Concatenation and Splitting

In [58]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print (np.concatenate([x,y]))

[1 2 3 3 2 1]


In [59]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


### It can also be used for two-dimensional arrays

In [60]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1) # second axis is col

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [63]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

 The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [64]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N split-points, leads to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar:

In [65]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [67]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
